import { StyleSheet } from "react-native";

export const s = StyleSheet.create({
  screen: { flex: 1 },
  safe: { flex: 1 },
  scroll: { paddingHorizontal: 16, paddingTop: 16, paddingBottom: 120, gap: 6 },
  blob: { position: "absolute", borderRadius: 999, opacity: 0.18 },
  blob1: { width: 300, height: 300, top: -80, left: -80 },
  blob2: { width: 240, height: 240, top: 300, right: -60 },
  blob3: { width: 180, height: 180, bottom: 100, left: 20 },
  profileBanner: { borderRadius: 18, overflow: "hidden", borderWidth: 1, marginBottom: 10 },
  profileInner: { flexDirection: "row", alignItems: "center", padding: 16, gap: 14 },
  avatar: { width: 56, height: 56, borderRadius: 28, borderWidth: 1, overflow: "hidden", alignItems: "center", justifyContent: "center" },
  avatarImage: { width: 56, height: 56, borderRadius: 28 },
  avatarInitials: { color: "#fff", fontSize: 18, fontWeight: "800", letterSpacing: 0.5 },
  profileText: { flex: 1 },
  profileName: { fontSize: 17, fontWeight: "700" },
  profileEmail: { fontSize: 13, marginTop: 2 },
  editBtn: { width: 34, height: 34, borderRadius: 10, backgroundColor: "rgba(74,159,232,0.12)", borderWidth: 1, borderColor: "rgba(74,159,232,0.25)", alignItems: "center", justifyContent: "center" },
  sectionTitle: { fontSize: 11, fontWeight: "700", letterSpacing: 1, textTransform: "uppercase", marginLeft: 4, marginBottom: 6, marginTop: 10 },
  section: { borderRadius: 16, overflow: "hidden", borderWidth: 1 },
  sectionShine: { position: "absolute", top: 0, left: 0, right: 0, height: 1 },
  row: { flexDirection: "row", alignItems: "center", paddingHorizontal: 14, paddingVertical: 13, gap: 12 },
  rowIcon: { width: 34, height: 34, borderRadius: 9, borderWidth: 1, alignItems: "center", justifyContent: "center" },
  rowIconDanger: { backgroundColor: "rgba(255,69,58,0.1)", borderColor: "rgba(255,69,58,0.2)" },
  rowText: { flex: 1 },
  rowLabel: { fontSize: 15, fontWeight: "500" },
  rowSublabel: { fontSize: 12, marginTop: 1 },
  badge: { backgroundColor: "rgba(74,159,232,0.2)", borderRadius: 8, paddingHorizontal: 8, paddingVertical: 2, borderWidth: 1, borderColor: "rgba(74,159,232,0.35)" },
  badgeText: { color: "#4A9FE8", fontSize: 11, fontWeight: "700" },
  footer: { fontSize: 12, textAlign: "center", marginTop: 8 },
});
